name: Fork Sync

on:
  schedule:
    - cron: '0 2-23/8 * * *'
  #manual trigger button
  workflow_dispatch:

jobs:
  sync:
    strategy:
      fail-fast: false
      matrix:
        branch: [master, development]
    runs-on: ubuntu-latest
    steps:
    - name: Sync ${{ matrix.branch }}
      uses: tgymnich/fork-sync@v1.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        owner: Haato3o
        base: ${{ matrix.branch }}
        head: ${{ matrix.branch }}
